# Generated by Django 4.2 on 2023-05-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_topic_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
    ]
